//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SysMon.rc
//
#define ID_REFRASH                      3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SYSMON_DIALOG               102
#define IDD_PROPPAGE_SERVICE            107
#define IDR_MAINFRAME                   128
#define IDD_PROPPAGE_SETTING            129
#define IDD_PROPPAGE_PROCESS            130
#define IDD_PROPPAGE_RULE               132
#define IDR_MENU_SYS                    133
#define IDD_PROPPAGE_SYSINFO            134
#define IDR_PROCESS                     135
#define IDR_MENU_PROCESS                135
#define IDD_PROPPAGE_TASK               136
#define IDR_MENU_SHELLICON              137
#define IDR_MENU_SERVICE                138
#define IDD_DIALOG_SVRSELECT            139
#define IDD_DIALOG1                     139
#define IDC_PROCLIST                    1000
#define ID_SETTING                      1001
#define IDC_STATICINFO                  1002
#define IDC_STATICPERC                  1003
#define ID_SHUTDOWN                     1004
#define IDC_LIST_PROCESS                1005
#define IDC_TYPESERVICES                1006
#define IDC_TYPEDRIVERS                 1007
#define IDC_VIEWRUNNING                 1008
#define IDC_VIEWSTOPED                  1009
#define IDC_VIEWALL                     1010
#define IDC_CREATESVR                   1011
#define IDC_VIEWLOG                     1012
#define IDC_TYPE                        1013
#define IDC_VIEW                        1014
#define IDC_SVRLIST                     1015
#define IDC_MEMORY                      1016
#define IDC_MEMORYPERCENT               1017
#define IDC_MEMORYPHYSICAL              1018
#define IDC_MEMORYPHYSICALLEFT          1019
#define IDC_MEMORYUSER                  1020
#define IDC_MEMORYUSERLEFT              1021
#define IDC_MEMORYPAGELEFT              1022
#define IDC_MEMORYPAGE                  1023
#define IDC_MEMPERCENT                  1024
#define IDC_MEMPHYSICAL                 1025
#define IDC_MEMPHYSICALLEFT             1026
#define IDC_MEMPAGE                     1027
#define IDC_MEMPAGELEFT                 1028
#define IDC_MEMUSER                     1029
#define IDC_MEMUSERLEFT                 1030
#define IDC_RESOURCE                    1031
#define IDC_RULELIST                    1033
#define IDC_RADIO_RESTART               1035
#define IDC_RADIO_REBOOT                1036
#define IDC_CHECK_SENDMSG               1037
#define IDC_EDIT_MSGTO                  1039
#define IDC_CHECK_RESOURCE              1040
#define IDC_EDIT_PERCENT                1041
#define IDC_BUTTON_ADDMON               1042
#define IDC_BUTTON_DECMON               1043
#define IDC_LIST_SELECT                 1044
#define IDC_BUTTON1                     1045
#define IDC_BUTTON2                     1046
#define IDC_CHECK_STARTMON              1047
#define IDC_CHECK1                      1048
#define IDC_EDIT2                       1050
#define IDC_CHECK2                      1051
#define IDC_EDIT3                       1052
#define IDC_EDIT4                       1053
#define IDC_CHECK3                      1054
#define IDC_EDIT5                       1055
#define IDC_SLIDER1                     1056
#define IDC_SLIDER2                     1057
#define IDC_SLIDER3                     1058
#define IDC_SLIDER4                     1059
#define IDC_SLIDER5                     1060
#define IDC_BUTTON3                     1061
#define IDC_BUTTON4                     1062
#define IDM_SYS_EXIT                    32771
#define IDM_SYS_HELP                    32772
#define IDR_SYS_ABOUT                   32773
#define IDM_PROC_TERMINATE              32774
#define IDM_PROC_REFRESH                32775
#define IDM_PROC_SENDMSG                32776
#define IDM_SHELLICON_EXIT              32778
#define IDM_SHELLICON_SHOWWINDOW        32779
#define IDM_SVR_LOAD                    32780
#define IDM_SVR_PAUSE                   32781
#define IDM_SVR_STOP                    32782
#define IDM_SVR_RESUME                  32783
#define IDM_SVR_REFRESH                 32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1062
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
